In [1]:
import torch
a = torch.arange(3).reshape((3, 1, 1))
b = torch.arange(4).reshape((1, 2, 2))
a, b

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]),
 tensor([[[0, 1],
          [2, 3]]]))

In [2]:
a + b

tensor([[[0, 1],
         [2, 3]],

        [[1, 2],
         [3, 4]],

        [[2, 3],
         [4, 5]]])

In [3]:
(a + b).shape

torch.Size([3, 2, 2])

In [4]:
(a + b).numel()

12